export const MESSAGE_TYPE = {
  INIT: 'init',
  CHANGE_INDEX: 'changeIndex',
  CHANGE_PROPS: 'changeProps',
  SET_CONFIG: 'setConfig',
  GET_CONFIG: 'getConfig',
  RETURN_CONFIG: 'returnConfig',
  SORT_COMPONENT: 'sortComponent',
  COPY_COMPONENT: 'copyComponent',
  DELETE_COMPONENT: 'deleteComponent',
  ADD_COMPONENT: 'addComponent',
  BEFORE_ADD_COMPONENT: 'beforeAddComponent',
  AFTER_ADD_COMPONENT: 'afterAddComponent',
  PREVIEW: 'preview',
};
